config/routes.rb
Triharder::Application.routes.draw do

  resources :my_time_trials

  resources :mycompetitions

  resources :myworkouts

  root :to => "homepage#index"
  match "homepage" => "homepage#index"

end

app/models/athlete.rb
class Athlete < ActiveRecord::Base
  attr_accessible :age, :aid, :email, :height, :name, :sport, :weight
end

app/models/coach.rb
class Coach < ActiveRecord::Base
  attr_accessible :coachid, :email, :name, :string, :team
end

app/models/my_time_trial.rb
class MyTimeTrial < ActiveRecord::Base
  attr_accessible :Date, :My_Time, :Other_Details, :Time_Trial_Type, :sport
end

app/models/mycompetition.rb
class Mycompetition < ActiveRecord::Base
  attr_accessible :Date, :My_result, :competition_Name, :other_details, :sport, :time
end

app/models/myjournal.rb
class Myjournal < ActiveRecord::Base
  attr_accessible :activity, :content, :name
end

app/models/myworkout.rb
class Myworkout < ActiveRecord::Base
  attr_accessible :Date, :details, :workouttype
end

app/models/scout.rb
class Scout < ActiveRecord::Base
  attr_accessible :email, :name, :scoutid, :string, :team
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
end

app/controllers/my_time_trial_controller.rb
class MyTimeTrialController < ApplicationController
end

app/controllers/my_time_trials_controller.rb
class MyTimeTrialsController < ApplicationController
  # GET /my_time_trials
  # GET /my_time_trials.json
  def index
    @my_time_trials = MyTimeTrial.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @my_time_trials }
    end
  end

  # GET /my_time_trials/1
  # GET /my_time_trials/1.json
  def show
    @my_time_trial = MyTimeTrial.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @my_time_trial }
    end
  end

  # GET /my_time_trials/new
  # GET /my_time_trials/new.json
  def new
    @my_time_trial = MyTimeTrial.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @my_time_trial }
    end
  end

  # GET /my_time_trials/1/edit
  def edit
    @my_time_trial = MyTimeTrial.find(params[:id])
  end

  # POST /my_time_trials
  # POST /my_time_trials.json
  def create
    @my_time_trial = MyTimeTrial.new(params[:my_time_trial])

    respond_to do |format|
      if @my_time_trial.save
        format.html { redirect_to @my_time_trial, :notice => 'My time trial was successfully created.' }
        format.json { render :json => @my_time_trial, :status => :created, :location => @my_time_trial }
      else
        format.html { render :action => "new" }
        format.json { render :json => @my_time_trial.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /my_time_trials/1
  # PUT /my_time_trials/1.json
  def update
    @my_time_trial = MyTimeTrial.find(params[:id])

    respond_to do |format|
      if @my_time_trial.update_attributes(params[:my_time_trial])
        format.html { redirect_to @my_time_trial, :notice => 'My time trial was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @my_time_trial.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /my_time_trials/1
  # DELETE /my_time_trials/1.json
  def destroy
    @my_time_trial = MyTimeTrial.find(params[:id])
    @my_time_trial.destroy

    respond_to do |format|
      format.html { redirect_to my_time_trials_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/myjournal_controller.rb
class MyjournalController < ApplicationController
end

app/controllers/myteam_controller.rb
class MyteamController < ApplicationController
end

app/controllers/myworkout_controller.rb
class MyworkoutController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/my_time_trial_helper.rb
module MyTimeTrialHelper
end

app/helpers/my_time_trials_helper.rb
module MyTimeTrialsHelper
end

app/helpers/mycompetition_helper.rb
module MycompetitionHelper
end

app/helpers/mycompetitions_helper.rb
module MycompetitionsHelper
end

app/helpers/myjournal_helper.rb
module MyjournalHelper
end

app/helpers/myjournals_helper.rb
module MyjournalsHelper
end

app/helpers/mysupliment_helper.rb
module MysuplimentHelper
end

app/helpers/myteam_helper.rb
module MyteamHelper
end

app/helpers/myworkout_helper.rb
module MyworkoutHelper
end

app/helpers/myworkouts_helper.rb
module MyworkoutsHelper
end

app/views/my_time_trials/_form.html.erb
<%= form_for(@my_time_trial) do |f| %>
  <% if @my_time_trial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@my_time_trial.errors.count, "error") %> prohibited this my_time_trial from being saved:</h2>

      <ul>
      <% @my_time_trial.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Time_Trial_Type %><br />
    <%= f.text_field :Time_Trial_Type %>
  </div>
  <div class="field">
    <%= f.label :sport %><br />
    <%= f.text_field :sport %>
  </div>
  <div class="field">
    <%= f.label :Date %><br />
    <%= f.date_select :Date %>
  </div>
  <div class="field">
    <%= f.label :My_Time %><br />
    <%= f.text_field :My_Time %>
  </div>
  <div class="field">
    <%= f.label :Other_Details %><br />
    <%= f.text_field :Other_Details %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/my_time_trials/edit.html.erb
<h1>Editing my_time_trial</h1>

<%= render 'form' %>

<%= link_to 'Show', @my_time_trial %> |
<%= link_to 'Back', my_time_trials_path %>

app/views/my_time_trials/index.html.erb
<h1>Listing my_time_trials</h1>

<table>
  <tr>
    <th>Time trial type</th>
    <th>Sport</th>
    <th>Date</th>
    <th>My time</th>
    <th>Other details</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @my_time_trials.each do |my_time_trial| %>
  <tr>
    <td><%= my_time_trial.Time_Trial_Type %></td>
    <td><%= my_time_trial.sport %></td>
    <td><%= my_time_trial.Date %></td>
    <td><%= my_time_trial.My_Time %></td>
    <td><%= my_time_trial.Other_Details %></td>
    <td><%= link_to 'Show', my_time_trial %></td>
    <td><%= link_to 'Edit', edit_my_time_trial_path(my_time_trial) %></td>
    <td><%= link_to 'Destroy', my_time_trial, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New My time trial', new_my_time_trial_path %>

app/views/my_time_trials/new.html.erb
<h1>New my_time_trial</h1>

<%= render 'form' %>

<%= link_to 'Back', my_time_trials_path %>

app/views/my_time_trials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Time trial type:</b>
  <%= @my_time_trial.Time_Trial_Type %>
</p>

<p>
  <b>Sport:</b>
  <%= @my_time_trial.sport %>
</p>

<p>
  <b>Date:</b>
  <%= @my_time_trial.Date %>
</p>

<p>
  <b>My time:</b>
  <%= @my_time_trial.My_Time %>
</p>

<p>
  <b>Other details:</b>
  <%= @my_time_trial.Other_Details %>
</p>


<%= link_to 'Edit', edit_my_time_trial_path(@my_time_trial) %> |
<%= link_to 'Back', my_time_trials_path %>