config/routes.rb
Triharder::Application.routes.draw do

  resources :my_time_trials

  resources :mycompetitions

  resources :myworkouts

  root :to => "homepage#index"
  match "homepage" => "homepage#index"

end

app/models/athlete.rb
class Athlete < ActiveRecord::Base
  attr_accessible :age, :aid, :email, :height, :name, :sport, :weight
end

app/models/coach.rb
class Coach < ActiveRecord::Base
  attr_accessible :coachid, :email, :name, :string, :team
end

app/models/my_time_trial.rb
class MyTimeTrial < ActiveRecord::Base
  attr_accessible :Date, :My_Time, :Other_Details, :Time_Trial_Type, :sport
end

app/models/mycompetition.rb
class Mycompetition < ActiveRecord::Base
  attr_accessible :Date, :My_result, :competition_Name, :other_details, :sport, :time
end

app/models/myjournal.rb
class Myjournal < ActiveRecord::Base
  attr_accessible :activity, :content, :name
end

app/models/myworkout.rb
class Myworkout < ActiveRecord::Base
  attr_accessible :Date, :details, :workouttype
end

app/models/scout.rb
class Scout < ActiveRecord::Base
  attr_accessible :email, :name, :scoutid, :string, :team
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
end

app/controllers/myjournal_controller.rb
class MyjournalController < ApplicationController
end

app/controllers/myjournals_controller.rb
class MyjournalsController < ApplicationController
  # GET /myjournals
  # GET /myjournals.json
  def index
    @myjournals = Myjournal.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @myjournals }
    end
  end

  # GET /myjournals/1
  # GET /myjournals/1.json
  def show
    @myjournal = Myjournal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @myjournal }
    end
  end

  # GET /myjournals/new
  # GET /myjournals/new.json
  def new
    @myjournal = Myjournal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @myjournal }
    end
  end

  # GET /myjournals/1/edit
  def edit
    @myjournal = Myjournal.find(params[:id])
  end

  # POST /myjournals
  # POST /myjournals.json
  def create
    @myjournal = Myjournal.new(params[:myjournal])

    respond_to do |format|
      if @myjournal.save
        format.html { redirect_to @myjournal, :notice => 'Myjournal was successfully created.' }
        format.json { render :json => @myjournal, :status => :created, :location => @myjournal }
      else
        format.html { render :action => "new" }
        format.json { render :json => @myjournal.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /myjournals/1
  # PUT /myjournals/1.json
  def update
    @myjournal = Myjournal.find(params[:id])

    respond_to do |format|
      if @myjournal.update_attributes(params[:myjournal])
        format.html { redirect_to @myjournal, :notice => 'Myjournal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @myjournal.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /myjournals/1
  # DELETE /myjournals/1.json
  def destroy
    @myjournal = Myjournal.find(params[:id])
    @myjournal.destroy

    respond_to do |format|
      format.html { redirect_to myjournals_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/myteam_controller.rb
class MyteamController < ApplicationController
end

app/controllers/myworkout_controller.rb
class MyworkoutController < ApplicationController
end

app/controllers/myworkouts_controller.rb
class MyworkoutsController < ApplicationController
  # GET /myworkouts
  # GET /myworkouts.json
  def index
    @myworkouts = Myworkout.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @myworkouts }
    end
  end

  # GET /myworkouts/1
  # GET /myworkouts/1.json
  def show
    @myworkout = Myworkout.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @myworkout }
    end
  end

  # GET /myworkouts/new
  # GET /myworkouts/new.json
  def new
    @myworkout = Myworkout.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @myworkout }
    end
  end

  # GET /myworkouts/1/edit
  def edit
    @myworkout = Myworkout.find(params[:id])
  end

  # POST /myworkouts
  # POST /myworkouts.json
  def create
    @myworkout = Myworkout.new(params[:myworkout])

    respond_to do |format|
      if @myworkout.save
        format.html { redirect_to @myworkout, :notice => 'Myworkout was successfully created.' }
        format.json { render :json => @myworkout, :status => :created, :location => @myworkout }
      else
        format.html { render :action => "new" }
        format.json { render :json => @myworkout.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /myworkouts/1
  # PUT /myworkouts/1.json
  def update
    @myworkout = Myworkout.find(params[:id])

    respond_to do |format|
      if @myworkout.update_attributes(params[:myworkout])
        format.html { redirect_to @myworkout, :notice => 'Myworkout was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @myworkout.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /myworkouts/1
  # DELETE /myworkouts/1.json
  def destroy
    @myworkout = Myworkout.find(params[:id])
    @myworkout.destroy

    respond_to do |format|
      format.html { redirect_to myworkouts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/my_time_trial_helper.rb
module MyTimeTrialHelper
end

app/helpers/my_time_trials_helper.rb
module MyTimeTrialsHelper
end

app/helpers/mycompetition_helper.rb
module MycompetitionHelper
end

app/helpers/mycompetitions_helper.rb
module MycompetitionsHelper
end

app/helpers/myjournal_helper.rb
module MyjournalHelper
end

app/helpers/myjournals_helper.rb
module MyjournalsHelper
end

app/helpers/mysupliment_helper.rb
module MysuplimentHelper
end

app/helpers/myteam_helper.rb
module MyteamHelper
end

app/helpers/myworkout_helper.rb
module MyworkoutHelper
end

app/helpers/myworkouts_helper.rb
module MyworkoutsHelper
end

app/views/myworkouts/_form.html.erb
<%= form_for(@myworkout) do |f| %>
  <% if @myworkout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@myworkout.errors.count, "error") %> prohibited this myworkout from being saved:</h2>

      <ul>
      <% @myworkout.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :workouttype %><br />
    <%= f.text_field :workouttype %>
  </div>
  <div class="field">
    <%= f.label :Date %><br />
    <%= f.date_select :Date %>
  </div>
  <div class="field">
    <%= f.label :details %><br />
    <%= f.text_field :details %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/myworkouts/edit.html.erb
<h1>Editing myworkout</h1>

<%= render 'form' %>

<%= link_to 'Show', @myworkout %> |
<%= link_to 'Back', myworkouts_path %>

app/views/myworkouts/index.html.erb
<h1>Listing myworkouts</h1>

<table>
  <tr>
    <th>Workouttype</th>
    <th>Date</th>
    <th>Details</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @myworkouts.each do |myworkout| %>
  <tr>
    <td><%= myworkout.workouttype %></td>
    <td><%= myworkout.Date %></td>
    <td><%= myworkout.details %></td>
    <td><%= link_to 'Show', myworkout %></td>
    <td><%= link_to 'Edit', edit_myworkout_path(myworkout) %></td>
    <td><%= link_to 'Destroy', myworkout, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Myworkout', new_myworkout_path %>

app/views/myworkouts/new.html.erb
<h1>New myworkout</h1>

<%= render 'form' %>

<%= link_to 'Back', myworkouts_path %>

app/views/myworkouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Workouttype:</b>
  <%= @myworkout.workouttype %>
</p>

<p>
  <b>Date:</b>
  <%= @myworkout.Date %>
</p>

<p>
  <b>Details:</b>
  <%= @myworkout.details %>
</p>


<%= link_to 'Edit', edit_myworkout_path(@myworkout) %> |
<%= link_to 'Back', myworkouts_path %>