config/routes.rb
Triharder::Application.routes.draw do

  resources :my_time_trials

  resources :mycompetitions

  resources :myworkouts

  root :to => "homepage#index"
  match "homepage" => "homepage#index"

end

app/models/athlete.rb
class Athlete < ActiveRecord::Base
  attr_accessible :age, :aid, :email, :height, :name, :sport, :weight
end

app/models/coach.rb
class Coach < ActiveRecord::Base
  attr_accessible :coachid, :email, :name, :string, :team
end

app/models/my_time_trial.rb
class MyTimeTrial < ActiveRecord::Base
  attr_accessible :Date, :My_Time, :Other_Details, :Time_Trial_Type, :sport
end

app/models/mycompetition.rb
class Mycompetition < ActiveRecord::Base
  attr_accessible :Date, :My_result, :competition_Name, :other_details, :sport, :time
end

app/models/myjournal.rb
class Myjournal < ActiveRecord::Base
  attr_accessible :activity, :content, :name
end

app/models/myworkout.rb
class Myworkout < ActiveRecord::Base
  attr_accessible :Date, :details, :workouttype
end

app/models/scout.rb
class Scout < ActiveRecord::Base
  attr_accessible :email, :name, :scoutid, :string, :team
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
end

app/controllers/mycompetition_controller.rb
class MycompetitionController < ApplicationController
end

app/controllers/mycompetitions_controller.rb
class MycompetitionsController < ApplicationController
  # GET /mycompetitions
  # GET /mycompetitions.json
  def index
    @mycompetitions = Mycompetition.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @mycompetitions }
    end
  end

  # GET /mycompetitions/1
  # GET /mycompetitions/1.json
  def show
    @mycompetition = Mycompetition.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @mycompetition }
    end
  end

  # GET /mycompetitions/new
  # GET /mycompetitions/new.json
  def new
    @mycompetition = Mycompetition.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @mycompetition }
    end
  end

  # GET /mycompetitions/1/edit
  def edit
    @mycompetition = Mycompetition.find(params[:id])
  end

  # POST /mycompetitions
  # POST /mycompetitions.json
  def create
    @mycompetition = Mycompetition.new(params[:mycompetition])

    respond_to do |format|
      if @mycompetition.save
        format.html { redirect_to @mycompetition, :notice => 'Mycompetition was successfully created.' }
        format.json { render :json => @mycompetition, :status => :created, :location => @mycompetition }
      else
        format.html { render :action => "new" }
        format.json { render :json => @mycompetition.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /mycompetitions/1
  # PUT /mycompetitions/1.json
  def update
    @mycompetition = Mycompetition.find(params[:id])

    respond_to do |format|
      if @mycompetition.update_attributes(params[:mycompetition])
        format.html { redirect_to @mycompetition, :notice => 'Mycompetition was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @mycompetition.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /mycompetitions/1
  # DELETE /mycompetitions/1.json
  def destroy
    @mycompetition = Mycompetition.find(params[:id])
    @mycompetition.destroy

    respond_to do |format|
      format.html { redirect_to mycompetitions_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/myjournal_controller.rb
class MyjournalController < ApplicationController
end

app/controllers/myteam_controller.rb
class MyteamController < ApplicationController
end

app/controllers/myworkout_controller.rb
class MyworkoutController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/my_time_trial_helper.rb
module MyTimeTrialHelper
end

app/helpers/my_time_trials_helper.rb
module MyTimeTrialsHelper
end

app/helpers/mycompetition_helper.rb
module MycompetitionHelper
end

app/helpers/mycompetitions_helper.rb
module MycompetitionsHelper
end

app/helpers/myjournal_helper.rb
module MyjournalHelper
end

app/helpers/myjournals_helper.rb
module MyjournalsHelper
end

app/helpers/mysupliment_helper.rb
module MysuplimentHelper
end

app/helpers/myteam_helper.rb
module MyteamHelper
end

app/helpers/myworkout_helper.rb
module MyworkoutHelper
end

app/helpers/myworkouts_helper.rb
module MyworkoutsHelper
end

app/views/mycompetitions/_form.html.erb
<%= form_for(@mycompetition) do |f| %>
  <% if @mycompetition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mycompetition.errors.count, "error") %> prohibited this mycompetition from being saved:</h2>

      <ul>
      <% @mycompetition.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :competition_Name %><br />
    <%= f.text_field :competition_Name %>
  </div>
  <div class="field">
    <%= f.label :sport %><br />
    <%= f.text_field :sport %>
  </div>
  <div class="field">
    <%= f.label :Date %><br />
    <%= f.date_select :Date %>
  </div>
  <div class="field">
    <%= f.label :My_result %><br />
    <%= f.text_field :My_result %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.text_field :time %>
  </div>
  <div class="field">
    <%= f.label :other_details %><br />
    <%= f.text_field :other_details %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mycompetitions/edit.html.erb
<h1>Editing mycompetition</h1>

<%= render 'form' %>

<%= link_to 'Show', @mycompetition %> |
<%= link_to 'Back', mycompetitions_path %>

app/views/mycompetitions/index.html.erb
<h1>Listing mycompetitions</h1>

<table>
  <tr>
    <th>Competition name</th>
    <th>Sport</th>
    <th>Date</th>
    <th>My result</th>
    <th>Time</th>
    <th>Other details</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mycompetitions.each do |mycompetition| %>
  <tr>
    <td><%= mycompetition.competition_Name %></td>
    <td><%= mycompetition.sport %></td>
    <td><%= mycompetition.Date %></td>
    <td><%= mycompetition.My_result %></td>
    <td><%= mycompetition.time %></td>
    <td><%= mycompetition.other_details %></td>
    <td><%= link_to 'Show', mycompetition %></td>
    <td><%= link_to 'Edit', edit_mycompetition_path(mycompetition) %></td>
    <td><%= link_to 'Destroy', mycompetition, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mycompetition', new_mycompetition_path %>

app/views/mycompetitions/new.html.erb
<h1>New mycompetition</h1>

<%= render 'form' %>

<%= link_to 'Back', mycompetitions_path %>

app/views/mycompetitions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Competition name:</b>
  <%= @mycompetition.competition_Name %>
</p>

<p>
  <b>Sport:</b>
  <%= @mycompetition.sport %>
</p>

<p>
  <b>Date:</b>
  <%= @mycompetition.Date %>
</p>

<p>
  <b>My result:</b>
  <%= @mycompetition.My_result %>
</p>

<p>
  <b>Time:</b>
  <%= @mycompetition.time %>
</p>

<p>
  <b>Other details:</b>
  <%= @mycompetition.other_details %>
</p>


<%= link_to 'Edit', edit_mycompetition_path(@mycompetition) %> |
<%= link_to 'Back', mycompetitions_path %>